Added tests for user admin
pymasterspl/reddit pull request #10
Opened 2024-05-14 12:53 UTC by bartczak-pa

2024-05-14 17:30 UTC, jacoor approved these changes
Approving, but please review comments. Some of those tests are good exercises but not needed in long run.

2024-05-14 17:30 UTC, jacoor commented on users/tests/user_admin_test.py
> +def test_add_fieldsets(model_admin: admin.ModelAdmin) -> None:
Good test.

2024-05-14 17:30 UTC, jacoor commented on users/tests/user_admin_test.py
> +def test_ordering(model_admin: admin.ModelAdmin) -> None:
This is a good exercise but not a needed test. You are testing what is provided and tested by Django (ordering)

2024-05-14 17:30 UTC, jacoor commented on users/tests/user_admin_test.py
> +    assert model_admin.list_display == DjangoUserAdmin.list_display[1:]
This is a good exercise but not a needed test. You are testing what is provided and tested by Django. Admin Panel that is.

2024-05-14 17:30 UTC, jacoor commented on users/tests/user_admin_test.py
> +    assert isinstance(model_admin, CustomUserAdmin)
Good one. Making sure it is our model.

2024-05-14 18:56 UTC, jacoor requested changes

2024-05-14 18:56 UTC, jacoor commented on pyproject.toml
> +[tool.pytest.ini_options]
Please move it to pytest.ini - people are more familiar with that file.

2024-05-14 18:56 UTC, jacoor commented
Actually, a change request

2024-05-16 09:11 UTC, jacoor commented
@bartczak-pa any movement here?

2024-05-16 10:17 UTC, bartczak-pa commented on users/tests/user_admin_test.py
> +def test_ordering(model_admin: admin.ModelAdmin) -> None:
This will be deleted with oncoming commit.

2024-05-16 10:42 UTC, jacoor commented on pyproject.toml
> +[tool.pytest.ini_options]
Please add pytest.ini .

2024-05-18 13:10 UTC, jacoor approved these changes

2024-05-20 12:33 UTC, jacoor commented
@bartczak-pa please merge

2024-05-21 09:34 UTC, merged