Feature/password recovery
pymasterspl/reddit pull request #29
Opened 2024-06-06 15:53 UTC by Pawelooo

Before starting, you must provide e-mail data

2024-06-06 16:05 UTC, jacoor requested changes

2024-06-06 16:05 UTC, jacoor commented on reddit/settings.py
> +EMAIL_HOST_USER = ""
this should be passed using env file, using config, like ie: secret key. You also need to update env-template file.

2024-06-06 16:05 UTC, jacoor commented on users/templates/users/password_reset_form.html
> +            {{form.as_p}}
Missing non field errors, check registration.html

2024-06-06 16:05 UTC, jacoor commented on users/templates/users/reset_password.html
> +                {% csrf_token %}
missing non field errors.

2024-06-08 07:08 UTC, jacoor commented
@Pawelooo let me know when this is ready for work by marking this as ready for review. Also please update branch from dev.

2024-06-08 07:17 UTC, Pawelooo commented
@jacoor now it is ready for checking. I have already updated the banch

2024-06-08 07:38 UTC, jacoor requested changes

2024-06-08 07:38 UTC, jacoor commented on reddit/settings.py
> +EMAIL_HOST = "smtp.gmail.com"
Tiny remark, I don't know why I did not think about it earlier. Here we are assuming everybody will use gmail. 
Please move host, host port, and use tls into config too. 
Sorry for not catching it earlier.

2024-06-08 07:38 UTC, jacoor commented on users/templates/users/reset_password.html
> +                {{ field.errors }}
This won't work. You are using field.errors not "non_field_errors" as was requested. Please check registration and just copy that code for non_field_errors here. 
Also I don't even know if field.errors exist.

2024-06-08 07:38 UTC, jacoor commented on users/templates/users/password_reset_form.html
> +            {{ field.errors }}
This won't work. You are using field.errors not "non_field_errors" as was requested. Please check registration and just copy that code for non_field_errors here. 
Also I don't even know if field.errors exist.

2024-06-09 10:56 UTC, Pawelooo commented
Everything has been added correctly and there is only one message

2024-06-09 11:08 UTC, jacoor requested changes

2024-06-09 11:08 UTC, jacoor commented on env-template
> +# EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True)
I don't think that this comment is needed. Everything is already in settings and self-explanatory. So please remove.

2024-06-09 11:08 UTC, jacoor commented on users/templates/users/password_reset_form.html
> +            {% if form.errors %}
This is not what I asked for. I asked for NON_FIELD_ERRORS. Again, check registration.

2024-06-09 11:08 UTC, jacoor commented on users/templates/users/password_reset_form.html
> +                            Your password can't be too similar to your other personal information.<br>
Why hardcoded? It should be provided by Django, if not, better to remove, cause ift may change in future version and it will create confusion.

2024-06-09 11:09 UTC, jacoor commented on users/templates/users/password_reset_form.html
> +            {% for field in form %}
Please use standard form.as_p or crispy forms. Do not duplicate work that django does for us.

2024-06-09 11:10 UTC, jacoor commented on users/templates/users/reset_password.html
> +                {% if form.errors %}
Please, use form.as_p or other build in form method.

2024-06-09 12:24 UTC, jacoor requested changes

2024-06-09 12:24 UTC, jacoor commented on env-template
> +# Your Login, Password, Host, Host port and TLS to MAIL  settings.py  should be as follow:
This is really not needed, this code is self explanatory.

2024-06-10 08:26 UTC, jacoor approved these changes

2024-06-10 08:34 UTC, merged