Feature/password recovery
pymasterspl/reddit pull request #36
Opened 2024-06-13 19:55 UTC by Pawelooo

2024-06-14 16:27 UTC, jacoor commented
Is this ready? Cause it's draft.

2024-06-24 17:19 UTC, jacoor commented
@Pawelooo how is it goign with this one?

2024-06-24 18:19 UTC, memorisanka commented on README.md
> +  * Then we return to the website https://myaccount.google.com in the input we enter app passwords or in Polish veriosn "hasła do aplikacji" ( it depends on the language setting on your account )
version

2024-06-24 18:19 UTC, memorisanka commented on README.md
> +
I would paste it before first possibility, and in "firs possibility" add information, that you need to enter the password in EMAIL_HOST_PASSWORD or something like this. 
```
   EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
   EMAIL_HOST = 'smtp.gmail.com'
   EMAIL_HOST_PORT = 587
   EMAIL_HOST_USER = 'your_name_email@gmail.com'
   EMAIL_HOST_PASSWORD = 'your_password'
   EMAIL_USE_TLS = True
   ```

2024-06-24 18:19 UTC, memorisanka commented on README.md
> +  * Place this code instead of the password -> EMAIL_HOST_PASSWORD.
Gmail returns you a code that you enter into the env file (EMAIL_HOST_PASSWORD).

2024-06-26 09:37 UTC, tgrycuk commented on env-template
>  EMAIL_HOST_PORT = 587
should be EMAIL_PORT not EMAIL_HOST_PORT (please change it in settings.py file)

2024-06-26 09:37 UTC, tgrycuk commented on README.md
> +   EMAIL_HOST_PORT = 587
should be EMAIL_PORT not EMAIL_HOST_PORT (change it please in settings.py file)

2024-06-26 09:50 UTC, tgrycuk requested changes
It may be worth considering doing password reset tests.

2024-06-26 09:50 UTC, tgrycuk commented on env-template
>  EMAIL_HOST_PORT = 587
```suggestion
EMAIL_PORT = 587
```

2024-06-26 09:50 UTC, tgrycuk commented on README.md
> +   EMAIL_HOST_PORT = 587
```suggestion
   EMAIL_PORT = 587
```

2024-06-27 21:41 UTC, tgrycuk approved these changes

2024-06-28 06:00 UTC, merged