several post-list fixes
pymasterspl/reddit pull request #50
Opened 2024-06-18 20:40 UTC by swietlikm

- fixed queryset of PostListView to .filter(parent=None)
- fixed misspelling in PostListView class
- fixed post list template for better displaying posts, fixed code for better readability

2024-06-19 08:02 UTC, jacoor requested changes

2024-06-19 08:02 UTC, jacoor commented on core/templates/core/post-list.html
> +                <div class="card-body border post-clickable" id="post-{{ post.id }}" data-url="{% url 'post-detail' post.id %}">
This post clickable thing is not so good...
How will it work w/o JS? Also, open in new tab will not work on it cause it is js. So really not good. 
Suggestion: add a traditional link (a) in the h3 below. 
Also, for post content, you need to strip tags. And I would also wrap it in href. This way, we don't need ".,post-clickable" at all. 
Please change. 
Javascript should be used as sugar, extra effects, not to handle core HTML functionality like linking.

2024-06-20 08:05 UTC, jacoor requested changes

2024-06-20 08:05 UTC, jacoor commented on core/templates/core/post-list.html
> +                    </a>
Incorrect HTML. 
A can not wrap h3. It needs to be other way around
h3 > a
Div > a

```suggestion
                    
                        <div class="card-body text-light">
                                <h3 class="h3"><a href="{% url 'post-detail' post.id %}" class="text-decoration-none">{{ post.title }}</a></h3>
                                <a href="{% url 'post-detail' post.id %}" class="text-decoration-none">{{ post.content|truncatechars:100 }}</a>
                        </div>
```
You also forgot to add tags stripping to truncate. What will heppen if there will be, ie <b> not closed in those 100 chars?

2024-06-20 12:38 UTC, jacoor requested changes
Still one remark.

2024-06-20 12:38 UTC, jacoor commented on core/templates/core/post-list.html
> +                <p class="mx-5">{{ post.content|truncatechars:100 }}</p>
Still, truncate chars require strip tags or other modifier, to remove html tags before truncate. If the test has any styling (might, in future) it will break.

2024-06-20 12:39 UTC, jacoor commented on core/templates/core/post-list.html
> +                <p class="mx-5">{{ post.content|truncatechars:100 }}</p>
prob this: https://www.w3schools.com/django/ref_filters_striptags.php

2024-06-20 13:09 UTC, jacoor approved these changes

2024-06-20 13:09 UTC, tgrycuk commented on core/templates/core/post-list.html
> +                <p class="mx-5">{{ post.content|truncatechars:100 }}</p>
done

2024-06-20 13:10 UTC, merged