Feature/account activation via link
pymasterspl/reddit pull request #53
Opened 2024-06-20 15:32 UTC by Pawelooo

2024-06-20 15:57 UTC, Pawelooo commented
I don't know if poetry.lock is OK because I only made poetry lock and it made a few changes

2024-06-21 10:10 UTC, jacoor requested changes
Nice work, couple improvements needed.

2024-06-21 10:10 UTC, jacoor commented on users/templates/users/account_activation_email.html
> +    <p>{{ domain }}{% url 'activate-account' uidb64=uid token=token %}</p>
Please double check if this has protocol - http or https.
I think I'd change domain to full server url like https://testserver.com/ 
Mind, http and https has to be dynamically generated.

2024-06-21 10:10 UTC, jacoor commented on users/tests/test_activate_account.py
> +    user.is_active = False
Please remove one, it's twice.

2024-06-21 10:10 UTC, jacoor commented on users/tests/test_activate_account.py
> +    user.refresh_from_db()
Refresh from db should be moved lower, before assert user.is_active. 
It's hard to correlate this with checking user.

2024-06-21 10:10 UTC, jacoor commented on users/tests/test_activate_account.py
> +    messages = list(get_messages(response.wsgi_request))
Should not there be only one message? So this should be easy check on message[0]?
and  assert len(messages) ==  1 no?
This way we have full control.

2024-06-21 10:10 UTC, jacoor commented on users/templates/users/account_activation_email.html
> +    <p>{{ domain }}{% url 'activate-account' uidb64=uid token=token %}</p>
Also, this is not a link - should be <a href...>

2024-06-21 10:10 UTC, jacoor commented on users/views.py
> +        activation_link = f"http://{self.request.get_host()}/{uid}/{token}/"
Hmm...
1. What is this activation_link for? I see it's used in send_email, but not in the email template. If you generated it then it should be used in both places. 
2. Also, I am missing here call to "reverse" or "reverse_lazy" to generate this url. 
3. The protocol should be https or http depending if we are on secure server...  An old topic: https://stackoverflow.com/a/21632907

2024-06-21 10:10 UTC, jacoor commented on users/views.py
> +            user = User.objects.get(pk=uid)
This should check if user is not active.

2024-06-22 09:56 UTC, jacoor requested changes
One small change and we are good. Ping on #reddit when ready please.

2024-06-22 09:56 UTC, jacoor commented on users/tests/test_activate_account.py
> +    user.refresh_from_db()
```suggestion
    user.refresh_from_db()
    assert user.is_active
```
This is what I ment. We still need to check if user is active, just keep it in one place.

2024-06-23 12:11 UTC, Pawelooo commented
@jacoor You can accept whatever

2024-06-24 09:28 UTC, jacoor approved these changes, later dismissed

2024-06-24 17:21 UTC, jacoor approved these changes
Looks good, but it will hang forever in QA because we need the instructions in other PR

2024-06-24 17:37 UTC, merged

2024-06-24 17:37 UTC, Pawelooo commented
I'm already adding documentation to the email