Added custom user model with customer user manager
pymasterspl/reddit pull request #6
Opened 2024-05-11 16:54 UTC by bartczak-pa

This overwrites default django behaviour and allows to create users based on email instead of username.

Can we check if this code is okay?

2024-05-11 17:51 UTC, jacoor commented
@bartczak-pa please see tests results. Those failed.
https://github.com/pymasterspl/reddit/actions/runs/9045129435/job/24854541143 
If you look here, it failed on migrations. This will be checked only after all is green. Please fix migrations.

2024-05-12 07:29 UTC, bartczak-pa commented
@jacoor Migrations are fixed and code is passing tests now.

2024-05-12 10:26 UTC, jacoor requested changes
The code looks good.
However, Ruff is configured on purpose to enforce typings. 
Please, do fix ruff errors and avoid #noqa unless really necessary. 
I pushed an example of type updates for you, please fix other missing types. 
If you have issues with typing, you can try to use AI to fix 
- copilot - ask it to add typings for you (this works)
- or copy the code to Chat GPT and ask to add types.
Of course, do not forget to use `ruff check --fix` for other issues. 
Again, only use #noqa if this is really necessary, like:
`users/models.py:29:19: TRY003 Avoid specifying long messages outside the exception class`, however, for this one google has very good answer you can find after couple seconds search:
https://docs.astral.sh/ruff/rules/raise-vanilla-args/
(I put "how to fix TRY003 Avoid specifying long messages outside the exception class`" as a question to google).

2024-05-12 10:32 UTC, jacoor commented on users/models.py
> +    def _create_user(self: "UserManager", email: str, password: str, **extra_fields: int) -> "User":
Here you have an example of added typings.

2024-05-12 10:33 UTC, jacoor commented on users/models.py
> +            message: str = "Users must have an email address"
And fixed ruff errors, this one is EM101

2024-05-13 09:57 UTC, jacoor commented
@bartczak-pa you need to resolve conflicts. After that, tests will start to run and we will know if the code good.

2024-05-13 10:09 UTC, jacoor approved these changes

2024-05-13 10:09 UTC, jacoor commented
Great work. Now merge away!

2024-05-13 10:10 UTC, bartczak-pa commented
Typings and conflicts are resolved.

2024-05-13 10:10 UTC, merged