Create test for base html
pymasterspl/reddit pull request #8
Opened 2024-05-12 15:03 UTC by Pawelooo

2024-05-14 17:30 UTC, jacoor commented
@Pawelooo where are we with this?

2024-05-14 18:13 UTC, Pawelooo commented
> @Pawelooo where are we with this?

@jacoor  I don't know how to write these tests so that they pass

2024-05-14 18:53 UTC, jacoor commented
Ok. So why did you not ask on Discord? That's why we are a team.

2024-05-14 19:00 UTC, jacoor requested changes

2024-05-14 19:00 UTC, jacoor commented on articles/tests/test_base_page.py
> +@pytest.mark.django_db()
this is not a function. Remove ()

2024-05-14 19:00 UTC, jacoor commented on articles/tests/test_base_page.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "reddit.settings")
you havev this in pytest.ini. Remove.

2024-05-14 19:00 UTC, jacoor commented on articles/tests/test_base_page.py
> +django.setup()
not needed.

2024-05-14 19:12 UTC, jacoor commented
Found it. 
please add "pytest-django" package to the project and remove articles/tests.py file.

2024-05-14 19:24 UTC, Pawelooo commented
![image](https://github.com/pymasterspl/reddit/assets/47075422/92649957-d168-4f30-85ea-ca48492129f9)
I pass these tests

2024-05-14 19:39 UTC, jacoor commented
And? Are you asking for something or stating something?
The tests here are not passing and this is the source of truth. 
Have you checked the failing tests here? There is clear into what is wrong.

2024-05-15 08:34 UTC, jacoor approved these changes

2024-05-15 18:00 UTC, merged